config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :events
  resources :trips
  root to: "calendars#index"

  get 'users/index', to: 'users#index'
  get 'users/show/:id', to: 'users#show'
  get 'calendars/index'
  get 'calendars/show'

  post '/trips/:id', to: 'trips#remove'
  post '/events/:id', to: 'trips#update'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/trip.rb
class Trip < ApplicationRecord
  has_and_belongs_to_many :events
  belongs_to :user
  validates :name, presence: true, length: {minimum: 1, maximum: 50}
  validates :description, presence: true, length: {minimum: 5, maximum: 140}
  validates :duration, presence: true, length: {minimum: 1, maximum: 240, too_long: "%{count / 24} days is the maximum allowed for an event. Try breaking your event up into smaller ones." }
  validates :start_time, uniqueness: { scope: :end_time, message: "Start time and end time must be different." }

  validate :start_must_be_before_end_time

  private

  def start_must_be_before_end_time
   errors.add(:start_time, "must be before end time") unless
      start_time < end_time
  end


end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  before_action :authenticate_user!

  def index
    @mytrips = current_user.trips.all
    @alltrips = Trip.all
  end

  def show
    find_trip
    @events =  @trip.events.all
    @markers = Gmaps4rails.build_markers(@events) do |event, marker|
      marker.lat event.latitude
      marker.lng event.longitude
      marker.infowindow event.description
    end
  end

  def new
    @trip = Trip.new
  end

  def edit
    find_trip
  end

  def create
    current_user
    @trip = Trip.new(trip_params)
    @trip.user_id = current_user.id
    @trip.duration = ((@trip.end_time - @trip.start_time) / 3600).round
    @trip.save
    if @trip.save
      redirect_to root_path
    else
      redirect_to new_trip_path, notice: @trip.errors.full_messages.last
    end
  end

  def update
    find_trip
      if trip_event_params[:event_ids]
        @event = Event.find(trip_event_params[:event_ids])
        if @event.start_time >= @trip.start_time
          if @trip.events.pluck(:event_id).include?(@event.id)
            flash[:notice] = 'This trip already includes this event.'
            redirect_to trip_path(@trip)
          else
            @trip.events << @event
            @trip.duration = ((@trip.end_time - @trip.start_time) / 3600).round
            @trip.save
            redirect_to trip_path(@trip)
          end
        else
          flash[:notice] = 'This event does not fall within your trip duration!'
          redirect_to @trip
        end
      else @trip.update(trip_params)
        @trip.duration = ((@trip.end_time - @trip.start_time) / 3600).round
        @trip.save
        redirect_to @trip
      end
  end

  def remove
    @trip = Trip.find(params[:id])
    for i in 0...@trip.events.length do
       if @trip.events[i].id == params[:eventid].to_i
         @trip.events.delete(@trip.events[i])
         @trip.duration = ((@trip.end_time - @trip.start_time) / 3600).round
         @trip.save
         break
       end
     end
     redirect_to trip_path(@trip)
    end

  def destroy
    find_trip
    @trip.destroy
    redirect_to '/'
  end

  private

  def trip_params
    params.require(:trip).permit(:name, :description, :start_time, :end_time, :trip_ids)
  end

  private
  def trip_event_params
    params.require(:trip).permit(:event_ids)
  end

  def get_event
    @event = Event.find_by_id(params[:id])
  end

  def find_trip
    @trip = Trip.find_by_id(params[:id])
  end
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/views/trips/edit.html.erb
<div class="container">
  <div class="row">
    <div class="one-half column" style="margin-top: 1%">
  <h1>Edit a Trip</h1>

  <% if current_user.id == @trip.user_id %>
    <%= form_with(model: @trip, local:true) do |f| %>
    <br>
    <%= f.label "Name: ", class: 'form-label' %>
    <%= f.text_field :name %>
    <br>
    <%= f.label "Description: ", class: 'form-label' %>
    <%= f.text_field :description %>
    <br>
    <%= f.label "Start time", class: 'form-label' %>
    <%= f.datetime_select :start_time, :default => Time.now, ampm: true %>
    <br>
    <%= f.label "End time", class: 'form-label' %>
    <%= f.datetime_select :end_time, :default => Time.now, ampm: true %>
    <br>
    <%= f.submit %>
  <% end %>
<% end %>
</div>
</div>
</div>

app/views/trips/index.html.erb
<div class="container">
  <div class="row">
    <div class="one-half column" style="margin-top: 1%">
      <h1>My Trips</h1>
      <ul style="list-style: none;">
        <% @mytrips.each do |trip| %>
          <li>
            <a href="/trips/<%= trip.id%>"><%= trip.name %></a>
            | Duration:
            <%= distance_of_time_in_words(trip.duration.hour) %>
          </li>
        <% end %>
      </ul>
      <h1>All trips</h1>
      <ul style="list-style: none;">
        <% @alltrips.each do |trip| %>
          <li>
            <a href="/trips/<%= trip.id%>"><%= trip.name %></a>
            |
            <%= trip.description %>
          </li>
        <% end %>
      </ul>
    </div>

    <div class="one-half column" style="margin-top: 1%">

      <%= form_with(model: Trip.new, local:true) do |f| %>
      <h1>Add a Trip</h1>
      <%= f.label "Name: ", class: 'form-label' %>
      <%= f.text_field :name %>
      <br>
      <%= f.label "Description: ", class: 'form-label' %>
      <%= f.text_field :description %>
      <br>
      <%= f.label "Start time", class: 'form-label' %>
      <%= f.datetime_select :start_time, :default => Time.now, ampm: true %>
      <br>
      <%= f.label "End time", class: 'form-label' %>
      <%= f.datetime_select :end_time, :default => Time.now, ampm: true %>
      <br>
      <%= f.submit %>
    <% end %>

    </div>
  </div>
</div>

app/views/trips/new.html.erb
<div class="container">
  <div class="row">
    <div class="one-half column" style="margin-top: 5%">
      <h1>Add a Trip</h1>

      <%= form_with(model: Trip.new, local:true) do |f| %>
      <br>
      <%= f.label "Name: ", class: 'form-label' %>
      <%= f.text_field :name %>
      <br>
      <%= f.label "Description: ", class: 'form-label' %>
      <%= f.text_field :description %>
      <br>
      <%= f.label "Start time", class: 'form-label' %>
      <%= f.datetime_select :start_time, :default => Time.now, ampm: true %>
      <br>
      <%= f.label "End time", class: 'form-label' %>
      <%= f.datetime_select :end_time, :default => Time.now, ampm: true %>
      <br>
      <%= f.submit %>
    <% end %>
  </div>
</div>
</div>

app/views/trips/show.html.erb
<div class="container">
  <div class="row">
    <div class="one-half column" style="margin-top: 1%">
      <h1><%= @trip.name %></h1>
      <h3>
        <i><%= @trip.description.capitalize %></i>
      </h3>
      <br>
      <p>This trip begins on
        <%= @trip.start_time.localtime.strftime("%B %d, %Y %I:%M %p") %></p>
      <p>and it ends on
        <%= @trip.end_time.localtime.strftime("%B %d, %Y %I:%M %p") %></p>
      <p>Total duration:
        <%= distance_of_time_in_words(@trip.duration.hour) %></p>
      <br>

      <% if @trip.events.empty? %>
        <p>You don't have any events assigned to this trip yet!</p>
      <% else %>
        <h4>There are currently
          <%= @trip.events.count %>
          assigned events:</h4>
        <% @trip.events.each do |event| %>
          <h4>
            <a href="/events/<%=event.id%>"><%=event.name%></a>
          </h4>
          <p>Description:
            <%= event.description %></p>
          <p>Start time:
            <%= event.start_time.localtime.strftime("%B %d, %Y %I:%M %p") %></p>
          <p>Duration:
            <%= distance_of_time_in_words(event.duration.hour) %></p>
          <% if @trip.user_id == current_user.id %>
            <%= link_to 'remove this event', "/trips/#{@trip.id}?eventid=#{event.id}", method: :post %>
          <% end %>
          <br>
        <% end %>
      <% end %>
      <br>
      <% if @trip.user_id == current_user.id %>
        <h3>Add an event to your trip:</h3>
        <%= form_with(model: @trip, local: true) do |f| %>
        <%= f.select :event_ids, options_from_collection_for_select(current_user.events.all, 'id', 'name') %>
        <%= f.submit "Assign"%>
      <% end %>
    <%end%>
    <% if current_user.id == @trip.user_id %>
      <%= link_to 'Edit trip', edit_trip_path(@trip) %>
      |
    <%= link_to 'Delete trip Forever', trip_path(@trip), method: :delete, data: { confirm: 'Are you sure?! No one else will be able to use your cool trip!' } %>
    <% end %>
  </div>

  <% if !@trip.events.empty? %>
    <div class="one-half column" style="margin-top: 1%">
      <div id="map" style='width: 320px; height: 320px;'></div>
    </div>
  </div>
<% end %>
</div>
</div>
</div>