config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :events
  resources :trips
  root to: "calendars#index"

  get 'users/index', to: 'users#index'
  get 'users/show/:id', to: 'users#show'
  get 'calendars/index'
  get 'calendars/show'

  post '/trips/:id', to: 'trips#remove'
  post '/events/:id', to: 'trips#update'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/event.rb
class Event < ApplicationRecord
  has_and_belongs_to_many :users
  has_and_belongs_to_many :trips
  validates :name, presence: true, length: {minimum: 1, maximum: 50}
  validates :description, presence: true, length: {minimum: 5, maximum: 140}
  validates :duration, presence: true, length: {minimum: 1, maximum: 12, too_long: "%{count} hours is the maximum allowed for an event. Try breaking your event up into smaller ones." }
  accepts_nested_attributes_for :trips

  geocoded_by :location
  after_validation :geocode
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!

  def index
    @events = Event.order(:id)
      if params[:order] == 'cost'
          @events = Event.all.order('cost')
      elsif params[:order] == 'name'
          @events = Event.all.order('name')
      elsif params[:order] == 'location'
          @events = Event.all.order('location')
      elsif params[:order] == 'start_time'
          @events = Event.all.order('start_time')
      elsif params[:order] == 'duration'
          @events = Event.all.order('duration')
      else
          @events = Event.all
      end
    @markers = Gmaps4rails.build_markers(@events) do |event, marker|
      marker.lat event.latitude
      marker.lng event.longitude
    end
  end

  def show
    @event = Event.find_by_id(params[:id])
    @event.end_time = @event.start_time + @event.duration.hours
    @trip = Trip.find_by_id(params[:id])
    @markers = Gmaps4rails.build_markers(@event) do |event, marker|
      marker.lat event.latitude
      marker.lng event.longitude
      marker.infowindow event.description
    end
  end

  def new
    @event = Event.new
  end

  def edit
    @event = Event.find_by_id(params[:id])
  end

  def create
    @event = Event.create(event_params)
    if @event.save
      @event.user_id = current_user.id
      current_user.events << @event
      redirect_to events_path
    else
      redirect_to new_event_path, notice: @event.errors.full_messages.each
    end
  end

  def update
    @event = Event.find_by_id(params[:id])
    @trip = Trip.find_by_id(event_trip_params[:trip_ids])
    if event_params[:name]
      if @event.update(event_params)
        @event.end_time = @event.start_time + @event.duration.hours
        redirect_to event_path(@event)
      else
        render 'edit'
      end
    elsif @event.start_time >= @trip.start_time && @event.start_time < @trip.end_time
      @trip.events << @event
      redirect_to trip_path(@trip) if @trip.save
    else
      flash[:notice] = 'This event starts before your trip, but you can still clone it at the bottom of this page!'
      redirect_to @event
    end
  end

  def destroy
    event = Event.find_by_id(params[:id])
    event.destroy

    redirect_to '/'
  end

  private

  def event_params
    params.require(:event).permit(:name, :description, :location, :start_time, :duration, :cost, :trip_ids)
  end

  def event_trip_params
    params.require(:event).permit(:trip_ids)
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<div class="indent-box">
<% if current_user.id == @event.user_id %>
<h2> Update Your Event </h2>
  <%= form_with(model: @event, local:true) do |f| %>
  <br>
  <%= f.label "Name: ", class: 'form-label' %>
  <%= f.text_field :name %>
  <br>
  <%= f.label "Description: ", class: 'form-label' %>
  <%= f.text_field :description %>
  <br>
  <%= f.label "Location: ", class: 'form-label' %>
  <%= f.text_field :location %>
  <br>
  <%= f.label "Start time", class: 'form-label' %>
  <%= f.datetime_select :start_time, :default => Time.now, ampm: true %>
  <br>
  <%= f.label "Duration", class: 'form-label' %>
  <span><%= f.select :duration, (1..10) %> hours</span>
  <%= f.label "Cost", class: 'form-label' %>
  <span>$<%= f.number_field :cost %></span>
  <p><%= f.submit %></p>
  <% end %>
<% else %>
  <h2> Clone this Event and add it to your Trip! </h2>
  <div class="form-wrapper">
  <div class='box two'>
  <%= form_with(model: Event.new, local: true) do |f| %>
  <br>
  <%= f.label "test", class: 'form-label' %>
  <%= f.text_field :name, value: @event.name %>
  <br>
  <%= f.label "Description: ", class: 'form-label' %>
  <%= f.text_field :description, value: @event.description %>
  <br>
  <%= f.label "Location: ", class: 'form-label' %>
  <%= f.text_field :location, value: @event.location %>
  <br>
  <%= f.label "Start time", class: 'form-label' %>
  <%= f.datetime_select :start_time %>
  <br>
  <%= f.label "Duration", class: 'form-label' %>
  <span><%= f.select :duration, (1..10) %> hours</span>
  <%= f.label "Cost", class: 'form-label' %>
  <span><%= f.number_field :cost, value: "$0.00" @event.cost %></span>
    <% if current_user.trips.empty? %>
      <p>You have no trips to add this to! But I guess you can clone it for later. </p>
    <% else %>
    <br>
      <%= f.label "Choose Trip", class: 'form-label' %>
      <%= f.select :trip_ids, options_from_collection_for_select(current_user.trips.all, 'id', 'name') %>
      <%= f.hidden_field :event, :value => @event.id%>
    <% end %>
    <br>
    <%= f.submit "Clone Me"%>
  </div>
  <div class='box one'>
  <p>You have trips from: </p>
  <ul style="list-style: none;">
    <% current_user.trips.each do |trip| %>
        <li>
          <a href="/trips/<%= trip.id%>"><%= trip.start_time.localtime.strftime("%B %d, %Y %I:%M %p") %> to <%= trip.end_time.localtime.strftime("%B %d, %Y %I:%M %p") %> </a>
        </li>
    <% end %>
  </ul>
  </div>
  <% end %>
<% end %>

</div>


</div>

app/views/events/destroy.html.erb
<h1>Events#destroy</h1>
<p>Find me in app/views/events/destroy.html.erb</p>

app/views/events/edit.html.erb
<div class="container">
  <div class="row">
    <div class="one-half column" style="margin-top: 1%">
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/events/index.html.erb
<div class="container">
  <div class="row">
    <div class="one-half column" style="margin-top: 1%">
      <h1>All events</h1>
      <p><h4>Sort by:</h4></p>
        <%= link_to "Cost", events_path(order: 'cost'), class: 'button' %>
        <%= link_to "Name", events_path(order: 'name'), class: 'button' %>
        <%= link_to "Location", events_path(order: 'location'), class: 'button' %>
        <br>
        <%= link_to "Start Time", events_path(order: 'start_time'), class: 'button' %>
        <%= link_to "Duration", events_path(order: 'duration'), class: 'button' %>

      <% @events.each do |event| %>
        <br>
        <a href="/events/<%= event.id%>"><%= event.name %></a>
        |
        <span><%= event.description %></span>
        |
        <span>$<%= event.cost %></span>
        <br>
      <% end %>
    </div>


  <div class="one-half column" style="margin-top: 1%">
    <div id="map" style='width: 320px; height: 320px;'></div>
    <br>
    <h1>Add an Event</h1>

    <%= form_with(model: Event.new, local:true) do |f| %>
    <br>
    <%= f.label "Name: ", class: 'form-label' %>
    <%= f.text_field :name %>
    <br>
    <%= f.label "Description: ", class: 'form-label' %>
    <%= f.text_field :description %>
    <br>
    <%= f.label "Location: ", class: 'form-label' %>
    <%= f.text_field :location %>
    <br>
    <%= f.label "Start time", class: 'form-label' %>
    <%= f.datetime_select :start_time, :default => Time.now, ampm: true %>
    <br>
    <%= f.label "Duration", class: 'form-label' %>
    <span><%= f.select :duration, (1..10) %>
      hours</span>
    <%= f.label "Cost $", class: 'form-label' %>
    <span><%= f.number_field :cost %></span>
    <p><%= f.submit %></p>
    <% end %>
  </div>
</div>


</div>

<script>
handler.getMap().setZoom(0);
</script>
</div>

app/views/events/new.html.erb
<div class="container">
  <div class="row">
    <div class="one-half column" style="margin-top: 1%">
      <h3>Add an Event</h3>

      <%= form_with(model: Event.new, local:true) do |f| %>
      <br>
      <%= f.label "Name: ", class: 'form-label' %>
      <%= f.text_field :name %>
      <br>
      <%= f.label "Description: ", class: 'form-label' %>
      <%= f.text_field :description %>
      <br>
      <%= f.label "Location: ", class: 'form-label' %>
      <%= f.text_field :location %>
      <br>
      <%= f.label "Start time", class: 'form-label' %>
      <%= f.datetime_select :start_time, :default => Time.now, ampm: true %>
      <br>
      <%= f.label "Duration", class: 'form-label' %>
      <span><%= f.select :duration, (1..10) %>
        hours</span>
      <%= f.label "Cost", class: 'form-label' %>
      <span>$<%= f.number_field :cost %></span>
      <p><%= f.submit %></p>
    <% end %>
  </div>
</div>
</div>

app/views/events/show.html.erb
<div class="container">
  <div class="row">
    <div class="one-half column" style="margin-top: 1%">

      <h2><%= @event.name %></h2>

      <h5>Host:
        <%= User.find(@event.user_id).fname %>
        <%= User.find(@event.user_id).lname %>
      </h5>

      <h4>
        Description:
      </h4>

      <%= @event.description %>

      <h4>
        Location:
      </h4>

      <%= @event.location %>

      <h4>
        Start Time:
      </h4>

      <%= @event.start_time.localtime.strftime("%B %d, %Y %I:%M %p") %>

      <h4>
        End Time:
      </h4>

      <%= @event.end_time.localtime.strftime("%B %d, %Y %I:%M %p") %>

      <h4>
        Cost:
      </h4>

      <span>$<%= @event.cost %></span>

      <h4>
        Duration:
      </h4>

      <p><%= distance_of_time_in_words(@event.duration.hour) %></p>

      <br>

    </div>

    <div class="one-half column" style="margin-top: 1%">
      <div id="map" style='width: 320px; height: 320px;'></div>

      <br>

      <% if current_user.id == @event.user_id %>
        <%= link_to 'Edit Event', edit_event_path(@event) %>
        |
      <%= link_to 'Delete Event Forever', event_path(@event), method: :delete, data: { confirm: 'Are you sure?! No one else will be able to use your cool event!' } %>
      <% end %>

      <% if !current_user.trips.empty? %>

        <h5>You're in town at the same time! Do you want to go?</h5>
        <%= form_with(model: @event, local: true) do |f| %>
        <%= f.select :trip_ids, options_from_collection_for_select(current_user.trips.all, 'id', 'name') %>
        <%= f.submit "Add to your trip!"%>
      <% end %>
    <% end %>

    <p>Want to do this exact thing at a later date? Clone the event below, and add it to your trip!
    </p>
    <%= link_to 'Yes, do it.', edit_event_path(@event) %>

  </div>
</div>
</div>

</div>

app/views/events/update.html.erb
<h1>Events#update</h1>
<p>Find me in app/views/events/update.html.erb</p>