config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :events
  resources :trips
  root to: "calendars#index"

  get 'users/index', to: 'users#index'
  get 'users/show/:id', to: 'users#show'
  get 'calendars/index'
  get 'calendars/show'

  post '/trips/:id', to: 'trips#remove'
  post '/events/:id', to: 'trips#update'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/calendar.rb
class Calendar < ApplicationRecord
  belongs_to :user
end

app/controllers/calendars_controller.rb
class CalendarsController < ApplicationController
  before_action :authenticate_user!

  def index
    @trips = current_user.trips.all
    @events = current_user.events.all
  end

  def show
    @date = params[:format]
    @trips = current_user.trips.all
  end
end

app/helpers/calendars_helper.rb
module CalendarsHelper
end

app/views/calendars/index.html.erb
<h3 style="text-align: center">Click on the highlighted day(s) to see your events!</h3>


<% @time1 = Time.new %>

  <%= month_calendar events: @trips do |date, trip| %>

  <% if @time1.day == date.day && !trip.empty? %>
      <div class="cal-day current-day has_trips"><%= link_to date.day, calendars_show_path(date) %>

  <% elsif @time1.day == date.day && trip.empty? %>
    <div class="cal-day current-day"><%= date.day %> </div>

  <% elsif @time1.day != date.day && !trip.empty? %>
      <% if @time1.month != date.month %>
      <div class="cal-day has_trips not-current-month"><%= link_to date.day, calendars_show_path(date) %>
      </div>
      <% else %>
      <div class="cal-day has_trips"><%= link_to date.day, calendars_show_path(date) %>
      </div>
      <% end %>

  <% else %>
  <% if @time1.month != date.month %>
    <div class="cal-day not-current-month"><%= date.day %></div>
  <% else %>
    <div class="cal-day"><%= date.day %></div>
  <% end %>

  <% end %>
<% end %>

app/views/calendars/show.html.erb
<div class="container">
  <div class="row">
    <div class="one-half column" style="margin-top: 1%">

      <h3>Today's Trip events</h3>
      <% @trips.each do |trip| %>
        <% trip.events.each do |event| %>
          <p>
            <% if event.start_time.to_date.to_s == @date.to_s %>
            </p>
            <p><%= link_to event.name, event_path(event) %>:
              <%= event.description %></p>
            <br>
          <% end %>
        <% end %>
      <% end %>
      <%= link_to "Add An Event", new_event_path %>
    </div>
  </div>
</div>