config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :events
  resources :trips
  root to: "calendars#index"

  get 'users/index', to: 'users#index'
  get 'users/show/:id', to: 'users#show'
  get 'calendars/index'
  get 'calendars/show'

  post '/trips/:id', to: 'trips#remove'
  post '/events/:id', to: 'trips#update'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Trippin</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag "normalize.css" %>
    <%= stylesheet_link_tag "skeleton.css" %>
    <!-- <link href="https://fonts.googleapis.com/css?family=Open+Sans+Condensed:300" rel="stylesheet"> -->

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag "https://maps.google.com/maps/api/js?v=3&key=#{ENV['GOOGLEMAPS_API_KEY']}" %>
    <script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
    <script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script>
    <!-- only if you need custom infoboxes -->
  </head>

  <nav class="navbar">
    <div>
      <%= link_to calendars_index_path do %>
      <%= image_tag "logo_black.png", size: "265x50" %>
    <% end %>
  </div>

  <div class="navlinks">
    <% if user_signed_in? %>
      <span>Logged in as:
        <%= link_to "/users/show/#{current_user.id}" do %>
          <%= current_user.fname %>
          <%= current_user.lname %>
        <% end %>
      </span>

      <br>

    <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %>
    |
    <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link' %>
    |
    <%= link_to "Calendar", "/" %>
    |
    <%= link_to "Events", events_path %>
    |
    <%= link_to "Trips", trips_path %>
  <% else %>
    <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link' %>
    |
    <%= link_to "Login", new_user_session_path, :class => 'navbar-link' %>
  <% end %>
  </div>


</nav>

<body>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<%= yield %>
</body>
<script type="text/javascript">
handler = Gmaps.build('Google');
handler.buildMap({
  provider: {},
  internal: {
    id: 'map'
  }
}, function () {
  markers = handler.addMarkers(<%=raw @markers.to_json %>);
  handler.bounds.extendWith(markers);
  handler.fitMapToBounds();
});
</script>

</html>